export const EDIT_ROW = 'EDIT_ROW'
export const UPLOAD_DATA = 'UPLOAD_DATA'

export const TOGGLE_DIRECTION = 'TOGGLE_DIRECTION'

export const CHANGE_MAP_TITLE = 'CHANGE_MAP_TITLE'
export const CHANGE_LINEAR_START_COLOR = 'CHANGE_LINEAR_START_COLOR'
export const CHANGE_LINEAR_END_COLOR = 'CHANGE_LINEAR_END_COLOR'
export const CHANGE_LINEAR_NO_DATA_COLOR = 'CHANGE_LINEAR_NO_DATA_COLOR'
