export const EDIT_ROW = 'EDIT_ROW'
export const UPLOAD_DATA = 'UPLOAD_DATA'
export const LOAD_EMPTY_DATA = 'LOAD_EMPTY_DATA'

export const TOGGLE_DIRECTION = 'TOGGLE_DIRECTION'

export const CHANGE_MAP_TITLE = 'CHANGE_MAP_TITLE'
export const CHANGE_LEGEND_TITLE = 'CHANGE_LEGEND_TITLE'
export const CHANGE_LINEAR_START_COLOR = 'CHANGE_LINEAR_START_COLOR'
export const CHANGE_LINEAR_END_COLOR = 'CHANGE_LINEAR_END_COLOR'
export const CHANGE_LINEAR_NO_DATA_COLOR = 'CHANGE_LINEAR_NO_DATA_COLOR'
export const CHANGE_DATA_CLASSIFICATION = 'CHANGE_DATA_CLASSIFICATION'
export const CHANGE_COLOR_PALLETE = 'CHANGE_COLOR_PALLETE'
export const CHANGE_CLASSES_COUNT = 'CHANGE_CLASSES_COUNT'
export const CHANGE_BORDER_COLOR = 'CHANGE_BORDER_COLOR'

export const CHANGE_DOMAIN_START_VALUE = 'CHANGE_DOMAIN_START_VALUE'
export const CHANGE_DOMAIN_END_VALUE = 'CHANGE_DOMAIN_END_VALUE'

export const REQUEST_TOPO_DATA = 'REQUEST_TOPO_DATA'
export const RECEIVE_TOPO_DATA = 'RECEIVE_TOPO_DATA'
export const SET_MAP_TYPE = 'SET_MAP_TYPE'
